version: "3"

services:
  wiremock-google:
    image: wiremock/wiremock:latest
    container_name: wiremock-google-api
    restart: always
    networks:
      - mycloudmen-network
    command: [ "--global-response-templating", "--verbose", "--root-dir", "/home/wiremock" ]
    volumes:
      - "./google-workspace/mappings:/home/wiremock/mappings"
      - "./google-workspace/__files:/home/wiremock/__files"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiremock-google.rule=Host(`mycloudmen.mennoplochaet.be`) && PathPrefix(`/google-workspace-api`)"
      - "traefik.http.services.wiremock-google.loadbalancer.server.port=8080"
      - "traefik.http.routers.wiremock-google.tls=true"
      - "traefik.http.routers.wiremock-google.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wiremock-google.entrypoints=websecure"
      - "traefik.http.middlewares.strip-google-api.stripprefix.prefixes=/google-workspace-api"
      - "traefik.http.routers.wiremock-google.middlewares=strip-google-api"

  wiremock-signature:
    image: wiremock/wiremock:latest
    container_name: wiremock-signature-api
    restart: always
    networks:
      - mycloudmen-network
    command: [ "--global-response-templating", "--verbose", "--root-dir", "/home/wiremock" ]
    volumes:
      - "./signature-satori/mappings:/home/wiremock/mappings"
      - "./signature-satori/__files:/home/wiremock/__files"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiremock-signature.rule=Host(`mycloudmen.mennoplochaet.be`) && PathPrefix(`/signature-satori-api`)"
      - "traefik.http.services.wiremock-signature.loadbalancer.server.port=8080"
      - "traefik.http.routers.wiremock-signature.tls=true"
      - "traefik.http.routers.wiremock-signature.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wiremock-signature.entrypoints=websecure"
      - "traefik.http.middlewares.strip-signature-api.stripprefix.prefixes=/signature-satori-api"
      - "traefik.http.routers.wiremock-signature.middlewares=strip-signature-api"
networks:
  mycloudmen-network:
    external: true
